sudo: false
dist: trusty
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
cache: pip
env:
  global:
    - CFLAGS="-coverage"
    - TRAVIS_TEST=true
  matrix:
    - MATPLOTLIB_VERSION=1.5.1
    - MATPLOTLIB_VERSION=2.2.3
    - MATPLOTLIB_VERSION=3.0.2
matrix:
  exclude:
  - python: 2.7
    env: MATPLOTLIB_VERSION=3.0.2
  - python: 3.4
    env: MATPLOTLIB_VERSION=3.0.2
install:
  - pip install --upgrade pip
  - pip install $(grep 'pytest' requirements.txt)
  - pip install coveralls coverage matplotlib==$MATPLOTLIB_VERSION
  - pip install -e .
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - py.test --cov=queueing_tool --cov-report term-missing --doctest-modules
after_success:
  - coveralls
